// Test-only credentials. They are not used by the application or suitable for deployment.
export const TEST_CA = `-----BEGIN CERTIFICATE-----
MIIBkzCCATmgAwIBAgIUFu/MtDW3xEdyVR7KFQ0FTui4TdEwCgYIKoZIzj0EAwIw
HzEdMBsGA1UEAwwUQ29kZXgtVmlld2VyLVRlc3QtQ0EwHhcNMjYwODAxMDczMjQz
WhcNMzYwNzI5MDczMjQzWjAfMR0wGwYDVQQDDBRDb2RleC1WaWV3ZXItVGVzdC1D
QTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABL6ARz9i/UYXW+2oveEwC2SdPf3j
mRp4lFOeHtEPV+c5p3u6GxLX451VsjqZP+h8iN1/T8sTy4DXm62KyuJl9NqjUzBR
MB0GA1UdDgQWBBTk5f6ftMezf97wGiEEb6URtu6zhTAfBgNVHSMEGDAWgBTk5f6f
tMezf97wGiEEb6URtu6zhTAPBgNVHRMBAf8EBTADAQH/MAoGCCqGSM49BAMCA0gA
MEUCIQCZvGJchEBJ1SioiIpxvFGOfL3/8n5rnrzZMaSR4AjbrAIgJuJfFHo0SlPf
UxEDBY27zKn7yXOanetqio7S0SDh4N8=
-----END CERTIFICATE-----`;

export const TEST_SERVER_CERTIFICATE = `-----BEGIN CERTIFICATE-----
MIIBhzCCAS6gAwIBAgIUOg/ydv9Bj6SDRN8DeP9N4HLy7bAwCgYIKoZIzj0EAwIw
HzEdMBsGA1UEAwwUQ29kZXgtVmlld2VyLVRlc3QtQ0EwHhcNMjYwODAxMDczMjQz
WhcNMzYwNzI5MDczMjQzWjAUMRIwEAYDVQQDDAkxMjcuMC4wLjEwWTATBgcqhkjO
PQIBBggqhkjOPQMBBwNCAAQ//d7FBYOEHBH1U1QphDClxDww9LY+BbHPWWnnLkm1
hRe5aRrQTPbW/OZ1E0+Rv0PxRpoBsoOox5zixIb/jdfTo1MwUTAPBgNVHREECDAG
hwR/AAABMB0GA1UdDgQWBBSSw4ijUkpg3p7RshEBQZ8TZv1FPDAfBgNVHSMEGDAW
gBTk5f6ftMezf97wGiEEb6URtu6zhTAKBggqhkjOPQQDAgNHADBEAiBDpXL+VQ2w
a/TKwlscixeiLr533/+DGhkCCKBFCruWVgIgbH/5u5MgaBwGb/316AI61QHVp45A
p+FPE+lEt2RQ+vA=
-----END CERTIFICATE-----`;

export const TEST_SERVER_KEY = `-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgbnlHCnJVPbTkaz0K
fzFiIZoTOVEqh5GPHo/TLzNZWYShRANCAAQ//d7FBYOEHBH1U1QphDClxDww9LY+
BbHPWWnnLkm1hRe5aRrQTPbW/OZ1E0+Rv0PxRpoBsoOox5zixIb/jdfT
-----END PRIVATE KEY-----`;

export const TEST_CLIENT_CERTIFICATE = `-----BEGIN CERTIFICATE-----
MIIBezCCASKgAwIBAgIUOg/ydv9Bj6SDRN8DeP9N4HLy7bEwCgYIKoZIzj0EAwIw
HzEdMBsGA1UEAwwUQ29kZXgtVmlld2VyLVRlc3QtQ0EwHhcNMjYwODAxMDczMjQz
WhcNMzYwNzI5MDczMjQzWjAZMRcwFQYDVQQDDA50cnVzdGVkLWNsaWVudDBZMBMG
ByqGSM49AgEGCCqGSM49AwEHA0IABCXhihKaPMSyLs2JJ6/N7avJTNPdWUDUzli5
jXDBXNtlSrAXYai2qUIOdiDNPZnAHAjfHYJCx1WiIpy/dC6vSL+jQjBAMB0GA1Ud
DgQWBBQcLQjMgWCCREvB+q4wmMukFfqCHjAfBgNVHSMEGDAWgBTk5f6ftMezf97w
GiEEb6URtu6zhTAKBggqhkjOPQQDAgNHADBEAiByVcuWIZ5rv5sc6AzV/EOW7gcr
4O3fKhImdLUZ6v7mdAIgCTVHtk0q2xUqjv3mXkhWRyLFkAHuPxbmF5V3+sUECNk=
-----END CERTIFICATE-----`;

export const TEST_CLIENT_KEY = `-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgJA8UFG5c2b59C8Gh
NH9qqn/NjMVxCSRcnt3Ou8kb+7yhRANCAAQl4YoSmjzEsi7NiSevze2ryUzT3VlA
1M5YuY1wwVzbZUqwF2GotqlCDnYgzT2ZwBwI3x2CQsdVoiKcv3Qur0i/
-----END PRIVATE KEY-----`;

export const TEST_UNTRUSTED_CLIENT_CERTIFICATE = `-----BEGIN CERTIFICATE-----
MIIBjDCCATGgAwIBAgIUc9nuvcyXh8imqErQEilLnia5c1owCgYIKoZIzj0EAwIw
GzEZMBcGA1UEAwwQdW50cnVzdGVkLWNsaWVudDAeFw0yNjA4MDEwNzMyNDNaFw0z
NjA3MjkwNzMyNDNaMBsxGTAXBgNVBAMMEHVudHJ1c3RlZC1jbGllbnQwWTATBgcq
hkjOPQIBBggqhkjOPQMBBwNCAATXEPXEoDkGPJyt1i6uDJE5JgEFJGxUW9e4FurI
k2NRX7hqSbdWEFf3ZvPPQipi8+ac+kGDqrD8tBeF0DTcV1b7o1MwUTAdBgNVHQ4E
FgQUTrbSgpm5iui0jS6pVj8oLFDskFMwHwYDVR0jBBgwFoAUTrbSgpm5iui0jS6p
Vj8oLFDskFMwDwYDVR0TAQH/BAUwAwEB/zAKBggqhkjOPQQDAgNJADBGAiEA0gvx
rfdiPpKbGr4guoj0xfy12KQ2ZtTxqAavBb8XPEICIQCRwEZW8znkHXkHQ6QLPB4C
ZTp/WZ3Fv/n4h4fy4YUuMw==
-----END CERTIFICATE-----`;

export const TEST_UNTRUSTED_CLIENT_KEY = `-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgkfKlrGU4KuyqZo/5
dwNUFBgMWMqTt4zNgs0nXVrjm4ahRANCAATXEPXEoDkGPJyt1i6uDJE5JgEFJGxU
W9e4FurIk2NRX7hqSbdWEFf3ZvPPQipi8+ac+kGDqrD8tBeF0DTcV1b7
-----END PRIVATE KEY-----`;
